[package]
name = "refinerox-back"
version = "0.1.0"
authors = ["Joost Yervante Damad <joost@damad.be>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"