[package]
name = "refinerox-front"
version = "0.1.0"
authors = ["Joost Yervante Damad <joost@damad.be>"]
edition = "2018"

[dependencies]
# local 0.5.0 version of yew
yew = { path = "../../wasm/yew" }
refinerox-data = { path = "../data" }

